### PR TITLE
Display information on channel bar mouse-over

### PR DESCRIPTION
**Pull request by r4d10n**
TODO: 
Stay lit on redraw.  
Changing to red for occupied channels would be really nice. How to handle transmissions spanning multiple band edges ?

### CODE REVIEW

**Comment by philcrump** [comment]
Thanks for the input, this feature has been asked for but I haven't got around to putting it together!

If you agree with the remove of `var signals = [];` on line 30 and can action that then I'll merge this in.

I may change the calling-flow of the mouseover later, as currently this'll break a couple of local apps that people use, but I'd far rather get this great feature in first and fix them later :)

**Comment by r4d10n** [comment]
Was curious about the signal blocks and tune code... Can you tell me what those local apps are ?

Also I can give a shot at the TODO feature for marking the active channels as red. But I see many folks crossing band edges. Any solutions ?

**Comment by philcrump** [comment]
Those blocks are part of another app I was working on: https://github.com/philcrump/longmynd , which includes the feed from this page as well as the main JS to create this local web interface: https://twitter.com/philcrump2/status/1248338645955883008 The reason it's in there is honestly self-serving - it means I don't have to update the longmynd app for a lot of the changes to the /wb/ page.

Marking active channels as red sounds interesting too! I'd make all channels that are overlapped red, to highlight the problems of not sticking to the bandplan.

FYI I've just made some changes, running the render function after each canvas refresh so the bar stays lit, and also de-duplicating the mouse event handlers with the stuff that was already in there. All pushed to master here.

**Comment by r4d10n** [comment]
Whoa... The screen grab looks really amazing... While doing this patch, I was hoping by a long shot that we could somehow (perhaps with leantrx?) decode the Callsign and also the MER at Goonhilly displayed on top of the signal bars ;) Are you planning to integrate it with the public interface sometime ? 

Just tested the new changes with rendering.... There seems to be random display of the "title" tip on doing some mouse overs across the spectrum plot region.. I guess it has do with the rendering / clearing on mouse leaves....

**Comment by philcrump** [comment]
I have been playing around with a 'scanning' mode for longmynd that displays the "Service Name" on top of the signals on the waterfall locally. Not 100% working well yet. I hadn't considered putting it on the public view that's a good idea, I'll talk to BATC and AMSAT-UK about it.

There was nothing to clear the 'title' attribute for the HTML element when a new render wasn't triggered. I've just fixed that.

**Comment by r4d10n** [comment]
Just found out Longmynd could work with Minitiouner Express... Hoping to experiment with that! 

Many thanks for the guidance and the quick fixes! Amazing work all you folks are doing out there for the hobby !

**Pull request merged**
