### PR TITLE
Channel Activity, Slot markers, dB value indicator

### PR DESCRIPTION
**Pull request by r4d10n**
1. As tried with the previous commit, signals[] array had to be initialized to enable computation of the signal markers for channel activity indicator and dB value display in the signal box. If it is breaking some dependency, kindly suggest better options.

2. In order to aid in reducing adjacent channel interference and locating free channels, line markers showing channel boundaries are shown on mouseover with channel numbers, which inturn could be used for referencing in chats. If this or any such assignment requires approval, kindly feel free to comment out the concerned portions.    

3. Kindly validate the dB calibration used for showing the value readout in graph. S-meter readout (above the beacon) on mouse over would be a nice addition, which can also later include Service Name and other parameters as suggested. 

4. Busy channel indicator spill-overs needs to be checked.

### CODE REVIEW

**Comment by r4d10n** [comment]
multi-channel signal

Spotted a wide multi-channel interferer :-)

**Comment by davecrump** [comment]
The dB level indication looks to be useful, but from a policy point of view, I am not sure that we want to try to enforce usage of specific channels on the web monitor.  It is more of a monitoring tool than an enforcing tool.  Very good work though!!

**Comment by philcrump** [comment]
The indicated C/N shown varies quite a bit during the day due to temperature, and of course with transponder usage, so I'm not sure that we want to advertise more precision than you can already see graphically.

Another option would be dB relative to the beacon, which doesn't suffer from either of these issues.

**Comment by r4d10n** [comment]
Many thanks for the feedback folks !

The intention for freq tooltips, (now) channel activity indicator and markers were just for ease of locating and configuring free channels for TX. I had enquired with @philcrump  [here](https://github.com/BritishAmateurTelevisionClub/eshail-ghy-web/pull/1#issuecomment-615981376_) in this context with regard to crossing the edges. Now that you have clarified that we do not intend to enforce, can you offer suggestion on how to go about it in the implementation ? One option is to just mark the occupied portion in red, without marking the whole channel bar as red. 

@philcrump Roger about the dB indicator. So signals below the beacon will be in -dB values ? And should we refer to it as dBB - as in dB Beacon?

**Comment by philcrump** [comment]
I'm not sure that trying to mark occupied channels is a great idea, we have had intermittent issues where the noise floor has risen and caused false signals to be 'detected' by the webpage, which would in case mark the whole band as 'occupied'. In addition we do encourage experimentation within and without the band plan.

As for the power measurement, I think dBb on mouseover would be a great feature to try.

**Comment by philcrump** [comment]
Thank you for taking the time to do this Rakesh - it looks great!

**Pull request merged**
